### ISSUE TITLE
Regression: `Error: Cannot find module 'eslint-config-prettier/prettier'` in 5.2.4

### ISSUE THREAD

**Issue by marekdedic** [prettier/eslint-plugin-prettier#717]
Hi,
I am getting this issue when updating from 5.2.3 to 5.2.4 - https://github.com/skaut/shared-drive-mover/pull/1959.

**Comment by JounQin** [comment]
Sorry for this, can you upgrade `eslint-config-prettier` as the same time?

**Comment by JounQin** [comment]
There is a few range of `eslint-config-prettier` we doesn't support due to its structure changes.

Only `>10.0.0 <10.1.0`, so is that worth to write the peer dependency range as `<10.0.0 || >=10.1.0`?

**Comment by marekdedic** [comment]
🤷 That's for you to decide, but it did break my update...

**Comment by JounQin** [comment]
@marekdedic Thanks for your input, v5.2.5 released with correct peer range.
